### ISSUE TITLE
mismatch db to model.py

### ISSUE THREAD

**Issue by alexfelmeister** [seg1129/CHOPSkillsAssessment#2]
You have a mismatch from your db which contains a NOT NULL constraint of the field collected_on, but the django model allows for a null. The field is not required on your form, so this causes an issue on save.

**Comment by seg1129** [comment]
Fixed issue in commit 3b953c387ab6662463b3afc09602a9b2369a7159. When using initial migrate function in django, the default is to make fields ‘not null’. Since sqlite3 does not support alter table remove constraints, I dropped the table and created a new one with out the constraints and imported original aliquot list.

**Comment by alexfelmeister** [comment]
👍
